sudo: required
language: groovy
jdk:
- openjdk7
services:
- postgresql
branches:
  only:
  - master
before_script:
- chmod +x grailsw
script: ./grailsw clean && ./grailsw refresh-dependencies && ./grailsw test-app --stacktrace
deploy:
  provider: heroku
  api_key:
    secure: Xt9u9vDgQIl5+vDXgOL+hBrIm9kBVJOWQ52kx9IDL4mTUmNdtiamctc+INzmbmRtq5kq/9mOql4SwXJtkU9lKQInZeq2rdO0VH6TL77kQB4LeUVYF41fokVdohR7BEo3IUIyjasQ3WEBwiuFE5nh44x1NTiXHG4zBUdA2/oFU+vOJGaBcVqpSWssmTA2OEOm6npY+GCkjI68NYz06xW6L2RKkO/LKYL90ulkT1d91g5oPwPazv2t1ROkbs3k4ZjF/Y+c6LzrqC3xyA898hbwdh6u8z9qxZbjL8YLsXHO6G+YfvhIrhQqyCKxqU5BtyTo6W7dLXix8NZW46JRBBlmgq1S6bpuzWXP/oHtMp3x33F5Y/W7x2jaCKxm+dqPzdM+10Ilj4L0mxiaWAqW0K08/yruws2QJQPOspwWEXiJ9sj+v9CGiniAbuEbDKJyTZYa8jmtxB2gObh9DqG7iVT3+KIfSR5630D1fevxUoVvxbAKK6KhJjGe+OIowSlJIp4XIN5J958dDYOxGikjMNPNFYIca4g3GRR5020wHokoCSdzaQbJ8W6c/4RnmekGmVB+q622woZspvpv/ZtmRleFlAMF6KhVIH+fOtj2RLcsff/JvKKNy4W0Y5h9eRaC5NCRQvr+Pzsa6TPwl/ABHOQzsdEZ1pVAqWuLFilkjxRr4is=
  app: mubs
  on:
    repo: biniama/mubs
