sudo: required
language: groovy
jdk:
- openjdk7
services:
- postgresql
branches:
  only:
  - master
before_script:
- chmod +x grailsw
script: ./grailsw clean && ./grailsw refresh-dependencies && ./grailsw test-app --stacktrace
deploy:
  provider: heroku
  api_key:
    secure: vfeSuILHabvhqaFlgHHw/ib6UTkCp4FZQVoX7GGZss1o+f6JmeeQN5iaPYkl4BtpcwGlUd4Sem/QmEsbQN/6MeNBbizaKlNzk33rsvraroDF557XyiLldB8eRwfMNQoTS5lrGofa+ls254THU6ev9mv9wxu/E9roh7U4WsouKLZghnjsUb5mlJ+u5DrcMOALDalTNbDV483TDfgLjy5Dm9p4LJAut+nrxpn0O/kbdnNYwg43Ts/4rP/vkSAbK9bgPJ2UQCW/Mafw+q9U8xQmSxb7qt/OSjSTLsPyQQJVmRQujiwrm6h4R/hDkDr88E3+VOX/p4nriCFKq3stKkDcAw+SjDB+KbR05sjVbWY8xbd4HVzp1qWYz2rNPEzWWZVA7l7EUCuAI037W3OHFNMHMx1uKAKj1QkuSpl07FEqW537ck3ohhUb9iP6AZrmJG+1z0aJ3+hsef8i8VcS0Q986L3iBkCujAmXwvRNr1JxPBzYrpC881wRSQScMaFxpVJUgBD0zhpfiaAXl1g/eClTvKe/5f8/8S6KtNnHdwwrl9mvcjEBq3qQe/daL8v1QD6z26QbpRnq2yAZuZ26TzKy/NSuMJL1LpzYtKVbAkro3YZ9wG67+HYrAs3UfdpAsoia5JEXEGs+iaPGZ89dbArg9zlIdZpJYRcoGDLgy7RchIs=
  app: mubs-stage
  on:
    repo: biniama/mubs
