sudo: required
language: groovy
jdk:
- oraclejdk8
services:
- postgresql
branches:
  only:
  - master
before_script:
- chmod +x grailsw
script: ./grailsw clean && ./grailsw refresh-dependencies && ./grailsw test-app --stacktrace
deploy:
  provider: heroku
  api_key:
    secure: G12MtXFz6y6axJCQyoByx0XZ4SXZzLKsJkNFbzWMUCHuWqy/MT9pUayDv3AMw71M/kQtRNxh8XVTNf+2K71IEUj4yQP1BRM21lx3rb+yQchBU8lWzS9CJ1jl20WaPPVDVJOX5ME7TfVzQD6fhsNBxXsFG4ExThwl7shgYK/97vygG5piRvA1cwpEQzji0gq3y8BSjXzQqklCEeYwRAZVkPn9Qx2yEyOzK2ljrJKVlXuaHhsP26paQaZFS5MCDCiCWRD0sjLAXL8qFF2gBNlHcsF5ET0WheCKUFlCmw+eNh6DaQ8XcipGwfT+5J3uzQmhp2zL0GJba0K+BlFfRjl+DdkJjFuHW1Fc2/dik0w2hc+3hYJIspJ9o11ALEqX+84+SYCEbj9YBFHee0JXdEV2dWiVjuB7p9AR/I9ObE6g4AFdwCeLITuEQK0jb4mfF1gtP43BLR64XT7tTXwGlpZOQh7Oo21R/z0xaYsB3lTQW8g6ABNDZsRj4A0/CobvxlbC/I6nsrmAxmPDpoqkqdFTOxKfjtz/OaAm0vG1sV1xdG1VqI6qfj/A88GdQctGBXLNdCEVQPBjAVZDRSiI24PpG7DVedqhSmE8hc8dWRZRn47AdySVXDLeqBwldAkiwyj8iX2+SEvSLSu2Lq9sDbs1Ct5+XogpYNCIm35fq/oIwbU=
  app: mubs
  on:
    repo: biniama/mubs
addons:
  sonarqube: true
env:
  global:
    secure: KN+aKoFVO1P1oqe/DSwlGQtDsDoVX7cpRa9rIy1CQg8w+GQB+GTmuU3d45WsRy7Iw11FdY0O3+hMFd4Q/NzKkknpkkRstAgR4Nmf/k5EORxzfERYl9hDP47Wy3QBU5TVDEFvYydS5AthVLUuuFK0AZ+MHga/La1UNP0DnwKL0b+/Ij2vnML01G9PybXfJ3zzQ/rVF3uHO+4XI9bosSafXhZOvHhEUevcc+3jruywEr5UB08itsOe6AmPV41+0j4H0qGjLD9QTeRFMwD6SP+Lgg70t3+qSmMs2S8qFd1lGZe9lSYjOg3ryxo+KDrYyc2aWKinODPIvEH+PFmUHAku4CyK8HYXwGHaCpTfuDYGYZeP0DmFOHu0YPLCZkVQjzNPuVA3gQ2/z7pFLGt1g4rMeWtTBdhzthHOeTla7ppHxBV7rC+CgbPluR3FaC88brK1x+uwB3+MeO207meba9uUQoBtTBr16rqGu9HhDabRTuQZpaouMrR0PUBmDdv/dya9vDnXWaiSycQwGwuB+xqcgItFoKhxr6fvScITMri5hJ6IpGVG3M3Rrf7gbDRZuOC4z2i0NxSNAAY+KCYXa0w1O6iz6zzU0MmA40Mcstdp+wNuauFW/LtKE4sa7wHvaHSdt944FGfYhrDTQEouxaD9upt0ok1R5vAJ45J2yRNkhds=
script:
  # other script steps might be done before running the actual SonarQube analysis
  - sonar-scanner -Dsonar.login=biniama
