sudo: required
language: groovy
jdk:
  - oraclejdk8
services:
- postgresql
branches:
  only:
  - master
before_script:
- chmod +x grailsw
script: ./grailsw clean && ./grailsw refresh-dependencies && ./grailsw test-app --stacktrace
deploy:
  provider: heroku
  api_key:
    secure: G12MtXFz6y6axJCQyoByx0XZ4SXZzLKsJkNFbzWMUCHuWqy/MT9pUayDv3AMw71M/kQtRNxh8XVTNf+2K71IEUj4yQP1BRM21lx3rb+yQchBU8lWzS9CJ1jl20WaPPVDVJOX5ME7TfVzQD6fhsNBxXsFG4ExThwl7shgYK/97vygG5piRvA1cwpEQzji0gq3y8BSjXzQqklCEeYwRAZVkPn9Qx2yEyOzK2ljrJKVlXuaHhsP26paQaZFS5MCDCiCWRD0sjLAXL8qFF2gBNlHcsF5ET0WheCKUFlCmw+eNh6DaQ8XcipGwfT+5J3uzQmhp2zL0GJba0K+BlFfRjl+DdkJjFuHW1Fc2/dik0w2hc+3hYJIspJ9o11ALEqX+84+SYCEbj9YBFHee0JXdEV2dWiVjuB7p9AR/I9ObE6g4AFdwCeLITuEQK0jb4mfF1gtP43BLR64XT7tTXwGlpZOQh7Oo21R/z0xaYsB3lTQW8g6ABNDZsRj4A0/CobvxlbC/I6nsrmAxmPDpoqkqdFTOxKfjtz/OaAm0vG1sV1xdG1VqI6qfj/A88GdQctGBXLNdCEVQPBjAVZDRSiI24PpG7DVedqhSmE8hc8dWRZRn47AdySVXDLeqBwldAkiwyj8iX2+SEvSLSu2Lq9sDbs1Ct5+XogpYNCIm35fq/oIwbU=
  app: mubs
  on:
    repo: biniama/mubs
