sudo: required
language: groovy
jdk:
    - openjdk7
services:
    - postgresql
branches:
    only:
        - master
before_script:
    - chmod +x grailsw
script: ./grailsw refresh-dependencies
    && ./grailsw test-app --stacktrace
deploy:
    provider: heroku
    api_key:
        secure: "CMAU3G0nWSuUOY0MqNt/pZ6G0VtUONCQV7X0MAFpd+drxYmafkD82jdddiZrXp74ypHJBL9ywfYbQPlyv/VGaf8pcyStDPOrBc6qOQSnyR7z446B4Db3587EV07A8jLmAx+m8nDzGoaYqIBnB6iN4QSs7e9Dmg/ml6HyQlPrBoW12+jHshLZGCG8jCAtvl2roYC3diGy4fpiCrQiTwqr3aE5t8E6c+5BcHLsW48+ADFzJwZyVj258kMx6RXyTTdN7gINPKJmQYD8MSW7PttXh61oqaqXJUYwT+2IVnk5cmoEsyk5VeeX1Gg8ICEbs00jK7pMiTgq4vLEp2CRXVF9N2Cs+33zkjZi05TCtjoBKgJc7FoGUlfiIpGM2fm10NvU+u7XOxyuGAGqr0fVhyZn+NtIo7sL3+dXAHVf5x9/HOA3iqTTIKiVMwueuhoAoh/dYzAwiup5IJnnLPqXBxKiPGhXcQNy/NI8tpiN8qpUR3CJ1YG5kg6IvuwzLU1yfbJmOvvPTJO6rZnwlLv6VsFdrOnU/VCstO6xsweCS+G7GXuHmG2BQi4SgBTQxb9uSt6Ia/QacoviZSsmuQojqKnV0pNX8jwLLOEaG2GrexGzsRfBbbSQ8bh5S4mrfEGJw5vHDa24UtpkW+mJQ4pZYUWgvn4hKOS1HUNd257muIUVauI="
    app:
        develop: mubs-stage
        master: mubs