sudo: required
language: groovy
jdk:
    - openjdk7
services:
    - mysql
branches:
    only:
        - master
before_script:
    - chmod +x grailsw
    - mysql -e 'create database mubs;'
script: ./grailsw refresh-dependencies
    && ./grailsw test-app
